// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDclFxQTeEy-qvcgZtYrISu3ouwFvd4zBM',
    appId: '1:284431376169:web:d47a6bbefeb36e9b172138',
    messagingSenderId: '284431376169',
    projectId: 'flutterdartprojeto',
    authDomain: 'flutterdartprojeto.firebaseapp.com',
    storageBucket: 'flutterdartprojeto.firebasestorage.app',
    measurementId: 'G-91Z39HGQMB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmOcfOs_rU3UoBnAWcyFOFyZTVbiNqisA',
    appId: '1:284431376169:android:4876ab74fa6783e3172138',
    messagingSenderId: '284431376169',
    projectId: 'flutterdartprojeto',
    storageBucket: 'flutterdartprojeto.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDclFxQTeEy-qvcgZtYrISu3ouwFvd4zBM',
    appId: '1:284431376169:web:2bf8871f8e5f0df9172138',
    messagingSenderId: '284431376169',
    projectId: 'flutterdartprojeto',
    authDomain: 'flutterdartprojeto.firebaseapp.com',
    storageBucket: 'flutterdartprojeto.firebasestorage.app',
    measurementId: 'G-SWQYVR5S7Z',
  );
}
